import type { Locale } from "./i18n.ts";
// Every shipped locale has complete coverage. No remote translations or runtime fallback service.
const locales: Locale[] = [
  "en",
  "es",
  "pt-BR",
  "fr",
  "de",
  "zh-CN",
  "ja",
  "ko",
];
const words = {
  walletTimeout: [
    "Connection timed out. Check your wallet, then try again.",
    "La conexión caducó. Revisa tu cartera y vuelve a intentarlo.",
    "A conexão expirou. Confira a carteira e tente novamente.",
    "La connexion a expiré. Vérifiez votre portefeuille et réessayez.",
    "Zeitüberschreitung. Wallet prüfen und erneut versuchen.",
    "连接超时。请检查钱包后重试。",
    "接続がタイムアウトしました。ウォレットを確認して再試行してください。",
    "연결 시간이 초과되었습니다. 지갑을 확인한 뒤 다시 시도하세요.",
  ],
  nativeHistory: [
    "Native pool history",
    "Historial del bote nativo",
    "Histórico do pool nativo",
    "Historique du pool natif",
    "Verlauf des nativen Pools",
    "原生奖池历史",
    "ネイティブプール履歴",
    "네이티브 풀 내역",
  ],
  nativeNet: [
    "Net change per LP share",
    "Cambio neto por participación LP",
    "Variação líquida por cota LP",
    "Variation nette par part LP",
    "Nettoänderung je LP-Einheit",
    "每份 LP 的净变化",
    "LP持分あたりの純変動",
    "LP 지분당 순변동",
  ],
  nativeHistoryHelp: [
    "Up to 60 settled draws, using the native LP accumulator so losses count too. This excludes personal gas, wrapper costs, Aave yield and borrowing. Past returns do not predict future returns.",
    "Hasta 60 sorteos liquidados con el acumulador LP, incluidas pérdidas. Excluye gas personal, bóvedas, rendimiento Aave y deuda. El pasado no predice retornos futuros.",
    "Até 60 sorteios liquidados pelo acumulador LP, incluindo perdas. Exclui gas pessoal, cofres, rendimento Aave e dívida. O passado não prevê retornos futuros.",
    "Jusqu’à 60 tirages réglés via l’accumulateur LP, pertes comprises. Hors gas personnel, coffres, rendement Aave et emprunts. Le passé ne prédit pas l’avenir.",
    "Bis zu 60 abgerechnete Ziehungen über den LP-Akkumulator, einschließlich Verlusten. Ohne persönliche Gas-, Vault- und Aave-Kosten oder Erträge. Vergangene Erträge sagen nichts über künftige aus.",
    "最多60次已结算开奖，使用原生 LP 累积因子，计入损失。不含个人 Gas、金库成本、Aave 收益和借贷。历史收益不代表未来收益。",
    "LP累積係数で最大60回の決済済み抽選を表示し、損失も反映。個人のガス代、ボールト費用、Aave収益・借入は除外。過去の収益は将来を予測しません。",
    "LP 누적 계수로 손실을 포함한 최대 60회 정산 추첨을 표시합니다. 개인 가스, 금고 비용, Aave 수익 및 차입은 제외합니다. 과거 수익은 미래 수익을 예측하지 않습니다.",
  ],
  contractWallet: [
    "Direct submission is not available for this contract wallet.",
    "El envío directo no está disponible para esta cartera de contrato.",
    "O envio direto não está disponível para esta carteira de contrato.",
    "L’envoi direct n’est pas disponible pour ce portefeuille contractuel.",
    "Direktes Senden ist für diese Vertrags-Wallet nicht verfügbar.",
    "此合约钱包不支持直接提交。",
    "このコントラクトウォレットでは直接送信できません。",
    "이 계약 지갑은 직접 제출을 지원하지 않습니다.",
  ],
  replacement: [
    "Sped up or cancelled?",
    "¿Acelerada o cancelada?",
    "Acelerada ou cancelada?",
    "Accélérée ou annulée ?",
    "Beschleunigt oder abgebrochen?",
    "已加速或取消？",
    "高速化・キャンセルしましたか？",
    "가속 또는 취소했나요?",
  ],
  transactionHash: [
    "Replacement transaction hash",
    "Hash de reemplazo",
    "Hash de substituição",
    "Hash de remplacement",
    "Hash der Ersatztransaktion",
    "替换交易哈希",
    "置換取引のハッシュ",
    "대체 거래 해시",
  ],
  connect: [
    "Connect wallet",
    "Conectar cartera",
    "Conectar carteira",
    "Connecter un portefeuille",
    "Wallet verbinden",
    "连接钱包",
    "ウォレットを接続",
    "지갑 연결",
  ],
  connected: [
    "Connected",
    "Conectada",
    "Conectada",
    "Connecté",
    "Verbunden",
    "已连接",
    "接続済み",
    "연결됨",
  ],
  coinbase: [
    "Coinbase Wallet",
    "Coinbase Wallet",
    "Coinbase Wallet",
    "Coinbase Wallet",
    "Coinbase Wallet",
    "Coinbase Wallet",
    "Coinbase Wallet",
    "Coinbase Wallet",
  ],
  pairing: [
    "On a laptop, scan the QR code with Coinbase Wallet on your phone. An installed Coinbase extension takes priority. Connecting grants no spending permission.",
    "En el portátil, escanea el QR con Coinbase Wallet en tu móvil. La extensión Coinbase instalada tiene prioridad. Conectar no autoriza gastos.",
    "No computador, leia o QR com Coinbase Wallet no celular. A extensão Coinbase instalada tem prioridade. Conectar não autoriza gastos.",
    "Sur ordinateur, scannez le QR avec Coinbase Wallet sur mobile. L’extension Coinbase installée est prioritaire. La connexion n’autorise aucune dépense.",
    "Am Laptop den QR-Code mit Coinbase Wallet am Handy scannen. Eine installierte Coinbase-Erweiterung hat Vorrang. Verbinden erlaubt keine Ausgaben.",
    "在电脑上打开后，用手机 Coinbase Wallet 扫描二维码。已安装的 Coinbase 扩展会优先使用。连接不会授予花费权限。",
    "PCのQRコードをスマートフォンのCoinbase Walletでスキャン。Coinbase拡張機能がある場合はそちらが優先されます。接続だけでは支出は許可されません。",
    "노트북의 QR 코드를 휴대폰 Coinbase Wallet로 스캔하세요. Coinbase 확장 프로그램이 설치되어 있으면 우선 사용됩니다. 연결만으로 지출 권한이 부여되지는 않습니다.",
  ],
  disconnect: [
    "Disconnect",
    "Desconectar",
    "Desconectar",
    "Déconnecter",
    "Trennen",
    "断开连接",
    "接続解除",
    "연결 해제",
  ],
  switchBase: [
    "Switch to Base",
    "Cambiar a Base",
    "Mudar para Base",
    "Passer sur Base",
    "Zu Base wechseln",
    "切换至 Base",
    "Baseに切り替え",
    "Base로 전환",
  ],
  working: [
    "Checking…",
    "Comprobando…",
    "Verificando…",
    "Vérification…",
    "Wird geprüft…",
    "检查中…",
    "確認中…",
    "확인 중…",
  ],
  tools: [
    "Your wallet, your call.",
    "Tu cartera, tu decisión.",
    "Sua carteira, sua decisão.",
    "Votre portefeuille, votre choix.",
    "Deine Wallet, deine Entscheidung.",
    "你的钱包，由你做主。",
    "あなたのウォレット、あなたの判断。",
    "내 지갑, 내 선택.",
  ],
  account: [
    "Wallet & position",
    "Cartera y posición",
    "Carteira e posição",
    "Portefeuille et position",
    "Wallet und Position",
    "钱包与头寸",
    "ウォレットとポジション",
    "지갑과 포지션",
  ],
  connectShort: [
    "Connect",
    "Conectar",
    "Conectar",
    "Connexion",
    "Verbinden",
    "连接",
    "接続",
    "연결",
  ],
  walletBalance: [
    "In your wallet",
    "En tu cartera",
    "Na sua carteira",
    "Dans votre portefeuille",
    "In deiner Wallet",
    "钱包余额",
    "ウォレット残高",
    "지갑 잔액",
  ],
  gas: [
    "Ether for network fees",
    "Ether para comisiones de red",
    "Ether para taxas de rede",
    "Ether pour les frais réseau",
    "Ether für Netzwerkgebühren",
    "用于网络费用的 Ether",
    "ネットワーク手数料用Ether",
    "네트워크 수수료용 Ether",
  ],
  review: [
    "Review",
    "Revisar",
    "Revisar",
    "Vérifier",
    "Prüfen",
    "核对",
    "確認",
    "검토",
  ],
  sign: [
    "Continue in wallet",
    "Continuar en la cartera",
    "Continuar na carteira",
    "Continuer dans le portefeuille",
    "In Wallet fortfahren",
    "在钱包中继续",
    "ウォレットで続ける",
    "지갑에서 계속",
  ],
  close: [
    "Close",
    "Cerrar",
    "Fechar",
    "Fermer",
    "Schließen",
    "关闭",
    "閉じる",
    "닫기",
  ],
  amount: [
    "Amount · USDC",
    "Importe · USDC",
    "Valor · USDC",
    "Montant · USDC",
    "Betrag · USDC",
    "金额 · USDC",
    "金額 · USDC",
    "금액 · USDC",
  ],
  deposit: [
    "Deposit USDC",
    "Depositar USDC",
    "Depositar USDC",
    "Déposer des USDC",
    "USDC einzahlen",
    "存入 USDC",
    "USDCを入金",
    "USDC 입금",
  ],
  withdraw: [
    "Request withdrawal",
    "Solicitar retiro",
    "Solicitar saque",
    "Demander un retrait",
    "Auszahlung anfordern",
    "申请提款",
    "出金を申請",
    "출금 요청",
  ],
  finalize: [
    "Collect withdrawal",
    "Cobrar retiro",
    "Receber saque",
    "Recevoir le retrait",
    "Auszahlung abholen",
    "领取提款",
    "出金を受け取る",
    "출금 수령",
  ],
  claim: [
    "Claim winnings",
    "Cobrar premios",
    "Resgatar prêmios",
    "Réclamer les gains",
    "Gewinne abholen",
    "领取奖金",
    "賞金を受け取る",
    "당첨금 수령",
  ],
  refund: [
    "Refund emergency tickets",
    "Reembolsar boletos de emergencia",
    "Reembolsar bilhetes em emergência",
    "Rembourser les billets en urgence",
    "Tickets im Notfall erstatten",
    "紧急退票退款",
    "緊急時のチケット返金",
    "긴급 티켓 환불",
  ],
  referral: [
    "Collect referral earnings",
    "Cobrar referidos",
    "Receber indicações",
    "Recevoir les parrainages",
    "Empfehlungserträge abholen",
    "领取推荐收益",
    "紹介報酬を受け取る",
    "추천 수익 수령",
  ],
  cancelSubscription: [
    "Cancel subscription & recover USDC",
    "Cancelar suscripción y recuperar USDC",
    "Cancelar assinatura e recuperar USDC",
    "Annuler l’abonnement et récupérer les USDC",
    "Abo beenden und USDC zurückholen",
    "取消订阅并取回 USDC",
    "定期購入を解除しUSDCを回収",
    "구독 취소 및 USDC 회수",
  ],
  cancelBatch: [
    "Cancel remaining order",
    "Cancelar pedido restante",
    "Cancelar pedido restante",
    "Annuler le reste de la commande",
    "Restauftrag stornieren",
    "取消剩余订单",
    "残りの注文をキャンセル",
    "남은 주문 취소",
  ],
  emergencyExit: [
    "Recover LP position",
    "Recuperar posición LP",
    "Recuperar posição LP",
    "Récupérer la position LP",
    "LP-Position zurückholen",
    "收回 LP 头寸",
    "LPポジションを回収",
    "LP 포지션 회수",
  ],
  revoke: [
    "Revoke USDC allowance",
    "Revocar permiso USDC",
    "Revogar permissão USDC",
    "Révoquer l’autorisation USDC",
    "USDC-Freigabe widerrufen",
    "撤销 USDC 授权",
    "USDC承認を取り消す",
    "USDC 승인 철회",
  ],
  approve: [
    "Approve exact USDC amount",
    "Aprobar el importe exacto de USDC",
    "Aprovar o valor exato de USDC",
    "Autoriser le montant exact d’USDC",
    "Genauen USDC-Betrag freigeben",
    "授权确切 USDC 金额",
    "正確なUSDC額を承認",
    "정확한 USDC 금액 승인",
  ],
  ticketIds: [
    "Ticket IDs",
    "IDs de boletos",
    "IDs dos bilhetes",
    "Identifiants des billets",
    "Ticket-IDs",
    "票据 ID",
    "チケットID",
    "티켓 ID",
  ],
  recovery: [
    "Recovery & permissions",
    "Recuperación y permisos",
    "Recuperação e permissões",
    "Récupération et autorisations",
    "Rückholung und Freigaben",
    "资金回收与授权",
    "回収と承認",
    "회수 및 권한",
  ],
  recoveryHelp: [
    "Subscription and remaining batch funds are separate. Cancel each to recover its balance. Revoking an allowance does not refund prepaid funds.",
    "Los fondos de suscripción y pedidos son independientes. Cancela cada uno. Revocar permisos no devuelve fondos prepagados.",
    "Assinatura e pedidos têm saldos separados. Cancele cada um. Revogar permissão não devolve pré-pagamentos.",
    "Abonnement et commande ont des soldes distincts. Annulez chacun. Révoquer une autorisation ne rembourse pas les fonds prépayés.",
    "Abo und Restauftrag haben getrennte Guthaben. Beide einzeln beenden. Ein Widerruf erstattet keine Vorauszahlungen.",
    "订阅和剩余批量订单资金独立。分别取消以取回余额。撤销授权不会退还预付资金。",
    "定期購入と残りの一括注文の資金は別です。それぞれ解除してください。承認取消だけでは前払金は戻りません。",
    "구독과 남은 일괄 주문 자금은 별개입니다. 각각 취소하세요. 승인 철회는 선불 자금을 환불하지 않습니다.",
  ],
  lp: [
    "Liquidity corner",
    "Rincón de liquidez",
    "Espaço de liquidez",
    "Coin liquidité",
    "Liquiditätsecke",
    "流动性专区",
    "流動性コーナー",
    "유동성 코너",
  ],
  lpHeading: [
    "Liquidity",
    "Liquidez",
    "Liquidez",
    "Liquidité",
    "Liquidität",
    "流动性",
    "流動性",
    "유동성",
  ],
  lpIntro: [
    "LPs supply the prize pool and share its gains and losses. Your capital can be lost. Withdrawals depend on draw settlement.",
    "Los LP aportan al bote y comparten ganancias y pérdidas. Puedes perder capital. Los retiros dependen del sorteo.",
    "LPs financiam os prêmios e compartilham ganhos e perdas. O capital pode ser perdido. Saques dependem do sorteio.",
    "Les LP financent les prix et partagent gains et pertes. Risque de perte du capital. Retraits après règlement du tirage.",
    "LPs finanzieren Gewinne und teilen Erträge und Verluste. Kapitalverlust möglich. Auszahlungen hängen vom Ziehungsabschluss ab.",
    "LP 为奖池提供资金并承担收益和损失。本金可能损失。提款取决于开奖结算。",
    "LPは賞金を供給し損益を分担します。元本損失の可能性があります。出金は抽選決済次第です。",
    "LP는 상금 풀을 공급하고 손익을 공유합니다. 원금 손실이 가능하며 출금은 추첨 정산에 달려 있습니다.",
  ],
  position: [
    "Position",
    "Posición",
    "Posição",
    "Position",
    "Position",
    "头寸",
    "ポジション",
    "포지션",
  ],
  activity: [
    "Activity",
    "Actividad",
    "Atividade",
    "Activité",
    "Aktivität",
    "活动",
    "履歴",
    "활동",
  ],
  details: [
    "Details",
    "Detalles",
    "Detalhes",
    "Détails",
    "Details",
    "详情",
    "詳細",
    "상세",
  ],
  vaults: [
    "Vaults",
    "Bóvedas",
    "Cofres",
    "Coffres",
    "Vaults",
    "金库",
    "ボールト",
    "금고",
  ],
  active: [
    "Active · estimated",
    "Activo · estimado",
    "Ativo · estimado",
    "Actif · estimation",
    "Aktiv · geschätzt",
    "活跃 · 估算",
    "稼働中 · 推定",
    "활성 · 추정",
  ],
  pendingDeposit: [
    "Waiting for settlement",
    "Esperando liquidación",
    "Aguardando liquidação",
    "En attente du règlement",
    "Wartet auf Abrechnung",
    "等待结算",
    "決済待ち",
    "정산 대기",
  ],
  exiting: [
    "Withdrawal requested · estimated",
    "Retiro solicitado · estimado",
    "Saque solicitado · estimado",
    "Retrait demandé · estimation",
    "Auszahlung angefordert · geschätzt",
    "提款已申请 · 估算",
    "出金申請済み · 推定",
    "출금 요청됨 · 추정",
  ],
  claimable: [
    "Ready to collect",
    "Listo para cobrar",
    "Pronto para receber",
    "Prêt à recevoir",
    "Bereit zur Auszahlung",
    "可领取",
    "受取可能",
    "수령 가능",
  ],
  headroom: [
    "Available capacity · not reserved",
    "Capacidad disponible · no reservada",
    "Capacidade disponível · sem reserva",
    "Capacité disponible · non réservée",
    "Freie Kapazität · nicht reserviert",
    "可用容量 · 未预留",
    "利用可能枠 · 未確保",
    "가용 용량 · 예약 안 됨",
  ],
  depositHelp: [
    "Accepted funds wait for this draw to settle. They cannot be cancelled normally. A full exit may require two draw settlements.",
    "Los fondos esperan la liquidación de este sorteo. No hay cancelación ordinaria. Salir puede requerir dos sorteos.",
    "Os fundos aguardam este sorteio. Não há cancelamento comum. A saída pode exigir dois sorteios.",
    "Les fonds attendent ce tirage. Pas d’annulation ordinaire. Une sortie complète peut nécessiter deux tirages.",
    "Einzahlungen warten auf diese Ziehung und sind regulär nicht stornierbar. Ein vollständiger Ausstieg kann zwei Ziehungen benötigen.",
    "已接受的资金等待本期开奖结算，通常无法取消。完全退出可能需要两次开奖结算。",
    "入金は今回の抽選決済を待ち、通常の取消はできません。全額出金に2回の決済が必要な場合があります。",
    "입금은 이번 추첨 정산을 기다리며 일반 취소는 불가합니다. 전체 출금에 두 번의 정산이 필요할 수 있습니다.",
  ],
  exitHelp: [
    "Request a percentage of available shares. Their value can change until settlement. Then collect USDC separately.",
    "Solicita un porcentaje de tus participaciones. Su valor cambia hasta liquidarse. Después cobra USDC.",
    "Solicite uma porcentagem das cotas. O valor varia até a liquidação. Depois receba USDC.",
    "Demandez un pourcentage des parts disponibles. Leur valeur varie jusqu’au règlement. Recevez ensuite les USDC.",
    "Anteil verfügbarer Einheiten anfordern. Der Wert kann bis zur Abrechnung schwanken. USDC anschließend abholen.",
    "申请提取可用份额的一定比例。结算前价值可能变化。随后单独领取 USDC。",
    "利用可能な持分の割合を申請。決済まで価値は変動します。その後USDCを別途受け取ります。",
    "가용 지분의 비율을 요청하세요. 정산까지 가치가 변동하며 이후 USDC를 별도로 수령합니다.",
  ],
  shares: [
    "Raw LP shares",
    "Participaciones LP sin escala",
    "Cotas LP brutas",
    "Parts LP brutes",
    "LP-Einheiten unskaliert",
    "LP 原始份额",
    "LP持分の生の値",
    "원시 LP 지분",
  ],
  allowance: [
    "USDC allowance to Jackpot",
    "Permiso USDC a Jackpot",
    "Permissão USDC ao Jackpot",
    "Autorisation USDC à Jackpot",
    "USDC-Freigabe für Jackpot",
    "对 Jackpot 的 USDC 授权",
    "JackpotへのUSDC承認",
    "Jackpot USDC 승인",
  ],
  destination: [
    "Contract destination",
    "Contrato de destino",
    "Contrato de destino",
    "Contrat destinataire",
    "Zielvertrag",
    "目标合约",
    "送信先コントラクト",
    "대상 계약",
  ],
  receive: [
    "Expected USDC · state may change",
    "USDC previsto · puede cambiar",
    "USDC esperado · pode mudar",
    "USDC estimés · état variable",
    "Erwartete USDC · veränderlich",
    "预期 USDC · 状态可能变化",
    "予想USDC · 状況で変動",
    "예상 USDC · 상태 변동 가능",
  ],
  noFee: [
    "Club fee: 0 · network fees apply",
    "Comisión Club: 0 · se cobra la red",
    "Taxa Club: 0 · taxas de rede à parte",
    "Frais Club : 0 · frais réseau en sus",
    "Club-Gebühr: 0 · Netzwerkgebühren fallen an",
    "Club 费用：0 · 需支付网络费用",
    "Club手数料：0 · ネットワーク手数料別",
    "Club 수수료: 0 · 네트워크 수수료 별도",
  ],
  rawTransaction: [
    "See Raw Transaction Info (Not Recommended)",
    "Ver información técnica de la transacción (no recomendado)",
    "Ver informações técnicas da transação (não recomendado)",
    "Voir les données brutes de la transaction (déconseillé)",
    "Rohe Transaktionsdaten anzeigen (nicht empfohlen)",
    "查看原始交易信息（不推荐）",
    "取引の生データを見る（非推奨）",
    "원시 거래 정보 보기 (권장하지 않음)",
  ],
  claimRefreshDelayed: [
    "Updates are delayed. We’ll check your claim again when you continue.",
    "Las actualizaciones se retrasan. Revisaremos tu cobro al continuar.",
    "As atualizações estão atrasadas. Verificaremos seu resgate ao continuar.",
    "Les mises à jour sont retardées. Votre retrait sera vérifié en continuant.",
    "Aktualisierungen verzögern sich. Beim Fortfahren prüfen wir die Auszahlung erneut.",
    "更新延迟。继续时会再次检查领取资格。",
    "更新が遅れています。続行時に再度確認します。",
    "업데이트가 지연되고 있습니다. 계속하면 수령 가능 여부를 다시 확인합니다.",
  ],
  reviewCancelled: [
    "This review was closed. Open it again to continue.",
    "Esta revisión se cerró. Ábrela de nuevo para continuar.",
    "Esta revisão foi fechada. Abra novamente para continuar.",
    "Cette vérification a été fermée. Rouvrez-la pour continuer.",
    "Diese Prüfung wurde geschlossen. Zum Fortfahren erneut öffnen.",
    "此核对已关闭。重新打开后可继续。",
    "確認画面が閉じられました。再度開いて続行してください。",
    "검토가 닫혔습니다. 다시 열어 계속하세요.",
  ],
  exactCall: [
    "Exact call",
    "Llamada exacta",
    "Chamada exata",
    "Appel exact",
    "Exakter Aufruf",
    "精确调用",
    "正確な呼び出し",
    "정확한 호출",
  ],
  approvalHelp: [
    "First approve this exact amount, then review the deposit again after confirmation. Approval alone does not deposit funds.",
    "Primero aprueba el importe exacto; después revisa el depósito. Aprobar no deposita fondos.",
    "Aprove o valor exato e revise o depósito após confirmar. Aprovação não deposita fundos.",
    "Autorisez ce montant, puis revérifiez le dépôt après confirmation. Autoriser ne dépose pas les fonds.",
    "Zuerst genauen Betrag freigeben, dann Einzahlung erneut prüfen. Die Freigabe allein zahlt nichts ein.",
    "先授权确切金额，确认后再核对存款。仅授权不会存入资金。",
    "まず正確な額を承認し、確定後に入金を再確認。承認だけでは入金されません。",
    "먼저 정확한 금액을 승인하고 확인 후 입금을 다시 검토하세요. 승인만으로 입금되지는 않습니다.",
  ],
  exportPosition: [
    "Export position passport",
    "Exportar posición",
    "Exportar posição",
    "Exporter la position",
    "Positionspass exportieren",
    "导出头寸快照",
    "ポジション情報を出力",
    "포지션 정보 내보내기",
  ],
  emptyActivity: [
    "No transactions on this device yet.",
    "Aún no hay transacciones en este dispositivo.",
    "Ainda não há transações neste dispositivo.",
    "Aucune transaction sur cet appareil.",
    "Noch keine Transaktionen auf diesem Gerät.",
    "本设备暂无交易。",
    "この端末に取引はまだありません。",
    "이 기기에 아직 거래가 없습니다.",
  ],
  wallet: [
    "Waiting for wallet",
    "Esperando cartera",
    "Aguardando carteira",
    "En attente du portefeuille",
    "Wartet auf Wallet",
    "等待钱包",
    "ウォレット待ち",
    "지갑 대기",
  ],
  pending: [
    "Pending confirmation",
    "Pendiente de confirmación",
    "Aguardando confirmação",
    "Confirmation en attente",
    "Bestätigung ausstehend",
    "等待确认",
    "承認待ち",
    "확인 대기",
  ],
  confirmed: [
    "Confirmed",
    "Confirmada",
    "Confirmada",
    "Confirmée",
    "Bestätigt",
    "已确认",
    "確定",
    "확인됨",
  ],
  reverted: [
    "Reverted · network fee paid",
    "Revertida · comisión de red pagada",
    "Revertida · taxa de rede paga",
    "Annulée par le contrat · frais réseau payés",
    "Zurückgesetzt · Netzwerkgebühr bezahlt",
    "已回滚 · 已支付网络费用",
    "リバート · ネットワーク手数料支払済み",
    "되돌림 · 네트워크 수수료 지불됨",
  ],
  replaced: [
    "Replaced with a different transaction",
    "Reemplazada por otra transacción",
    "Substituída por outra transação",
    "Remplacée par une autre transaction",
    "Durch andere Transaktion ersetzt",
    "已被不同交易替换",
    "別の取引に置換",
    "다른 거래로 대체됨",
  ],
  unknown: [
    "Check your wallet before trying again",
    "Revisa tu cartera antes de reintentar",
    "Confira a carteira antes de tentar novamente",
    "Vérifiez votre portefeuille avant de réessayer",
    "Vor erneutem Versuch Wallet prüfen",
    "重试前请检查钱包",
    "再試行前にウォレットを確認",
    "재시도 전 지갑 확인",
  ],
  rejected: [
    "Declined in wallet",
    "Rechazada en la cartera",
    "Recusada na carteira",
    "Refusée dans le portefeuille",
    "In Wallet abgelehnt",
    "已在钱包中拒绝",
    "ウォレットで拒否",
    "지갑에서 거절됨",
  ],
  refresh: [
    "Refresh",
    "Actualizar",
    "Atualizar",
    "Actualiser",
    "Aktualisieren",
    "刷新",
    "更新",
    "새로고침",
  ],
  dismissUnknown: [
    "I checked: this was not submitted",
    "Comprobado: no se envió",
    "Conferi: não foi enviada",
    "Vérifié : rien n’a été envoyé",
    "Geprüft: nicht gesendet",
    "已确认：未提交此交易",
    "確認済み：送信されていません",
    "확인함: 제출되지 않았습니다",
  ],
  notDeployed: [
    "Not deployed · deposits unavailable",
    "Sin desplegar · depósitos no disponibles",
    "Não implantado · depósitos indisponíveis",
    "Non déployé · dépôts indisponibles",
    "Nicht bereitgestellt · keine Einzahlungen",
    "未部署 · 无法存款",
    "未デプロイ · 入金不可",
    "미배포 · 입금 불가",
  ],
  plans: [
    "My plans",
    "Mis planes",
    "Meus planos",
    "Mes plans",
    "Meine Pläne",
    "我的计划",
    "マイプラン",
    "내 계획",
  ],
  bonus: [
    "Bonus number",
    "Número adicional",
    "Número bônus",
    "Numéro bonus",
    "Bonuszahl",
    "特别号码",
    "ボーナス数字",
    "보너스 번호",
  ],
  quickPick: [
    "Surprise me",
    "Sorpréndeme",
    "Surpreenda-me",
    "Surprenez-moi",
    "Überrasch mich",
    "随机选号",
    "おまかせ",
    "무작위 선택",
  ],
  once: [
    "One draw",
    "Un sorteo",
    "Um sorteio",
    "Un tirage",
    "Eine Ziehung",
    "一次开奖",
    "1回の抽選",
    "한 번의 추첨",
  ],
  daily: [
    "Daily",
    "Diaria",
    "Diária",
    "Quotidienne",
    "Täglich",
    "每日",
    "毎日",
    "매일",
  ],
  delete: [
    "Delete",
    "Eliminar",
    "Excluir",
    "Supprimer",
    "Löschen",
    "删除",
    "削除",
    "삭제",
  ],
  export: [
    "Export",
    "Exportar",
    "Exportar",
    "Exporter",
    "Exportieren",
    "导出",
    "出力",
    "내보내기",
  ],
  unavailable: [
    "This action is not available in the current contract state.",
    "Acción no disponible en el estado actual.",
    "Ação indisponível no estado atual.",
    "Action indisponible dans l’état actuel.",
    "Aktion im aktuellen Vertragszustand nicht verfügbar.",
    "当前合约状态下无法执行此操作。",
    "現在のコントラクト状態では実行できません。",
    "현재 계약 상태에서 실행할 수 없습니다.",
  ],
  failed: [
    "Could not verify this action. Check your connection settings, refresh and try again.",
    "No se pudo verificar. Revisa la conexión, actualiza y reintenta.",
    "Não foi possível verificar. Confira a conexão, atualize e tente novamente.",
    "Vérification impossible. Vérifiez la connexion, actualisez et réessayez.",
    "Prüfung fehlgeschlagen. Verbindung prüfen, aktualisieren und erneut versuchen.",
    "无法验证此操作。请检查连接设置、刷新并重试。",
    "操作を検証できません。接続設定を確認し、更新して再試行してください。",
    "작업을 검증할 수 없습니다. 연결 설정을 확인하고 새로고침 후 재시도하세요.",
  ],
  invalidAmount: [
    "Enter a positive USDC amount with at most 6 decimal places.",
    "Introduce USDC positivo con hasta 6 decimales.",
    "Informe USDC positivo com até 6 casas decimais.",
    "Saisissez un montant USDC positif avec 6 décimales maximum.",
    "Positiven USDC-Betrag mit höchstens 6 Nachkommastellen eingeben.",
    "请输入正数 USDC 金额，最多6位小数。",
    "正のUSDC額を小数点以下6桁以内で入力。",
    "소수점 6자리 이내의 양수 USDC 금액을 입력하세요.",
  ],
  invalidTickets: [
    "Enter 1–30 unique, positive ticket IDs.",
    "Introduce 1–30 IDs únicos positivos.",
    "Informe 1–30 IDs positivos únicos.",
    "Saisissez 1 à 30 identifiants positifs distincts.",
    "1–30 eindeutige positive Ticket-IDs eingeben.",
    "请输入1–30个唯一的正整数票据ID。",
    "重複しない正のチケットIDを1〜30件入力。",
    "중복 없는 양수 티켓 ID 1~30개를 입력하세요.",
  ],
  walletChanged: [
    "Wallet or network changed. Review this action again.",
    "Cartera o red cambiada. Revisa de nuevo.",
    "Carteira ou rede mudou. Revise novamente.",
    "Portefeuille ou réseau modifié. Revérifiez l’action.",
    "Wallet oder Netzwerk geändert. Aktion erneut prüfen.",
    "钱包或网络已变更。请重新核对操作。",
    "ウォレットまたはネットワークが変更されました。再確認してください。",
    "지갑 또는 네트워크가 변경되었습니다. 다시 검토하세요.",
  ],
  reviewChanged: [
    "The quote changed. Review the updated action before signing.",
    "La cotización cambió. Revisa antes de firmar.",
    "A cotação mudou. Revise antes de assinar.",
    "L’estimation a changé. Revérifiez avant de signer.",
    "Angebot geändert. Vor dem Signieren erneut prüfen.",
    "报价已变化。签名前请重新核对。",
    "見積りが変更されました。署名前に再確認してください。",
    "견적이 변경되었습니다. 서명 전에 다시 검토하세요.",
  ],
  insufficientBalance: [
    "Your wallet does not have enough Base USDC.",
    "Tu cartera no tiene suficiente USDC en Base.",
    "Sua carteira não tem USDC suficiente na Base.",
    "Solde USDC sur Base insuffisant.",
    "Nicht genügend USDC auf Base in deiner Wallet.",
    "钱包中的 Base USDC 不足。",
    "BaseのUSDC残高が不足しています。",
    "지갑의 Base USDC가 부족합니다.",
  ],
  insufficientGas: [
    "You need more Ether on Base for network fees.",
    "Necesitas más Ether en Base para la red.",
    "Você precisa de mais Ether na Base para taxas.",
    "Il faut plus d’Ether sur Base pour les frais réseau.",
    "Mehr Ether auf Base für Netzwerkgebühren erforderlich.",
    "需要更多 Base Ether 支付网络费用。",
    "手数料用のBase Etherが不足しています。",
    "수수료를 위한 Base Ether가 더 필요합니다.",
  ],
  noCapacity: [
    "The pool has insufficient capacity for this deposit. No funds were submitted.",
    "El bote no tiene capacidad suficiente. No se enviaron fondos.",
    "O pool não tem capacidade suficiente. Nada foi enviado.",
    "Capacité du pool insuffisante. Aucun fonds envoyé.",
    "Pool-Kapazität reicht nicht. Keine Mittel gesendet.",
    "奖池容量不足，尚未提交资金。",
    "プールの空き枠が不足。資金は送信されていません。",
    "풀 용량이 부족합니다. 자금은 제출되지 않았습니다.",
  ],
  drawLocked: [
    "This deposit or withdrawal request must wait until the draw unlocks.",
    "Espera al desbloqueo del sorteo para depositar o solicitar retiro.",
    "Aguarde o desbloqueio do sorteio para depositar ou solicitar saque.",
    "Attendez le déverrouillage du tirage pour déposer ou demander un retrait.",
    "Einzahlung oder Auszahlungsanfrage muss auf Freigabe der Ziehung warten.",
    "存款或提款申请须等待开奖解锁。",
    "入金・出金申請は抽選ロック解除までお待ちください。",
    "입금 또는 출금 요청은 추첨 잠금 해제를 기다려야 합니다.",
  ],
  nothingAvailable: [
    "There is nothing available for this action right now.",
    "No hay saldo disponible para esta acción.",
    "Não há saldo disponível para esta ação.",
    "Rien n’est disponible pour cette action.",
    "Für diese Aktion ist derzeit nichts verfügbar.",
    "目前没有可用于此操作的余额。",
    "現在この操作の対象はありません。",
    "현재 이 작업에 사용할 수 있는 잔액이 없습니다.",
  ],
  notOwner: [
    "The connected account does not currently own every ticket.",
    "La cuenta no es dueña de todos los boletos.",
    "A conta não possui todos os bilhetes.",
    "Le compte ne possède pas tous les billets.",
    "Das verbundene Konto besitzt nicht alle Tickets.",
    "当前连接账户并非所有票据的持有人。",
    "接続アカウントはすべての券を保有していません。",
    "연결 계정이 모든 티켓을 보유하고 있지 않습니다.",
  ],
  notWinner: [
    "A supplied ticket has no payout. It was excluded from claiming to avoid burning it.",
    "Un boleto no tiene premio. No se reclamó para evitar quemarlo.",
    "Um bilhete não tem prêmio. O resgate foi impedido para não queimá-lo.",
    "Un billet n’a aucun gain. La demande est bloquée pour éviter de le brûler.",
    "Ein Ticket hat keinen Gewinn. Anspruch blockiert, um es nicht zu verbrennen.",
    "某票据没有奖金。已阻止领取以避免销毁该票据。",
    "当選金がない券が含まれるため、バーンを避けて停止しました。",
    "당첨금이 없는 티켓이 있어 소각을 방지하기 위해 수령이 중단되었습니다.",
  ],
  notSettled: [
    "One of these drawings has not settled yet.",
    "Un sorteo aún no se ha liquidado.",
    "Um dos sorteios ainda não foi liquidado.",
    "Un de ces tirages n’est pas encore réglé.",
    "Eine dieser Ziehungen ist noch nicht abgerechnet.",
    "其中一个开奖尚未结算。",
    "未決済の抽選が含まれています。",
    "추첨 중 하나가 아직 정산되지 않았습니다.",
  ],
  contractChanged: [
    "Contract identity differs from the reviewed deployment. New transactions are blocked.",
    "La identidad del contrato cambió. Se bloquearon nuevas transacciones.",
    "A identidade do contrato mudou. Novas transações bloqueadas.",
    "L’identité du contrat a changé. Nouvelles transactions bloquées.",
    "Vertragsidentität weicht ab. Neue Transaktionen sind gesperrt.",
    "合约身份与已核验部署不符。已阻止新交易。",
    "コントラクトが検証済み版と異なります。新規取引を停止。",
    "계약이 검토된 배포와 다릅니다. 새 거래가 차단되었습니다.",
  ],
  unresolvedTransaction: [
    "Resolve your pending wallet request or transaction before starting another.",
    "Resuelve la solicitud o transacción pendiente antes de otra.",
    "Resolva a solicitação ou transação pendente antes de outra.",
    "Résolvez la demande ou transaction en cours avant de continuer.",
    "Offene Wallet-Anfrage oder Transaktion zuerst klären.",
    "开始新交易前，请先处理待完成的钱包请求或交易。",
    "新しい操作の前に未処理のリクエストや取引を確認してください。",
    "새 작업 전 대기 중인 지갑 요청 또는 거래를 해결하세요.",
  ],
  ambiguousTransaction: [
    "The wallet response is unclear. Check the wallet and activity before trying again; the transaction may already be submitted.",
    "Respuesta incierta. Revisa cartera y actividad antes de reintentar; puede estar enviada.",
    "Resposta incerta. Confira carteira e atividade antes de tentar; pode ter sido enviada.",
    "Réponse incertaine. Vérifiez portefeuille et activité avant de réessayer ; l’envoi a peut-être eu lieu.",
    "Wallet-Antwort unklar. Wallet und Verlauf prüfen; die Transaktion könnte bereits gesendet sein.",
    "钱包响应不明确。重试前请检查钱包和活动；交易可能已提交。",
    "ウォレットの応答が不明です。送信済みの可能性があるため、再試行前に履歴を確認してください。",
    "지갑 응답이 불분명합니다. 이미 제출되었을 수 있으니 재시도 전 지갑과 활동을 확인하세요.",
  ],
  walletPending: [
    "A wallet request is already open. Check your wallet.",
    "Ya hay una solicitud abierta. Revisa tu cartera.",
    "Já há uma solicitação aberta. Confira a carteira.",
    "Une demande est déjà ouverte. Vérifiez votre portefeuille.",
    "Eine Wallet-Anfrage ist offen. Wallet prüfen.",
    "已有钱包请求待处理，请检查钱包。",
    "ウォレットリクエストが開いています。確認してください。",
    "지갑 요청이 이미 열려 있습니다. 지갑을 확인하세요.",
  ],
  storageFailed: [
    "Browser storage is unavailable. Export your work before closing this page.",
    "Almacenamiento no disponible. Exporta antes de cerrar.",
    "Armazenamento indisponível. Exporte antes de fechar.",
    "Stockage indisponible. Exportez avant de fermer.",
    "Browserspeicher nicht verfügbar. Vor dem Schließen exportieren.",
    "浏览器存储不可用。关闭页面前请导出。",
    "ブラウザー保存が使えません。閉じる前に出力してください。",
    "브라우저 저장소를 사용할 수 없습니다. 닫기 전에 내보내세요.",
  ],
} as const;
export type ClubKey = keyof typeof words;
export function clubCopy(locale: Locale) {
  const i = locales.indexOf(locale);
  return (key: ClubKey) => words[key][i];
}
export function errorCopy(locale: Locale, error: unknown) {
  let key =
    error instanceof Error
      ? error.message
      : typeof error === "string"
        ? error
        : "failed";
  if (key === "reviewExpired") key = "reviewChanged";
  if (["wrongChain", "connectFirst"].includes(key)) key = "walletChanged";
  return clubCopy(locale)(key in words ? (key as ClubKey) : "failed");
}
export const clubKeys = Object.keys(words) as ClubKey[];
