import { LANGUAGES, type Locale } from "./i18n.ts";

const words = {
  upcoming: [
    "Upcoming",
    "Próximos",
    "Próximos",
    "À venir",
    "Bevorstehend",
    "即将开奖",
    "これからの抽選",
    "다가오는 추첨",
  ],
  past: [
    "Past draws",
    "Sorteos anteriores",
    "Sorteios anteriores",
    "Tirages passés",
    "Vergangene Ziehungen",
    "往期开奖",
    "過去の抽選",
    "지난 추첨",
  ],
  collection: [
    "Your collection",
    "Tu colección",
    "Sua coleção",
    "Votre collection",
    "Deine Sammlung",
    "您的彩票集",
    "あなたのコレクション",
    "내 컬렉션",
  ],
  allNumbers: [
    "Your numbers",
    "Tus números",
    "Seus números",
    "Vos numéros",
    "Deine Zahlen",
    "您的号码",
    "あなたの番号",
    "내 번호",
  ],
  viewTickets: [
    "View tickets",
    "Ver boletos",
    "Ver bilhetes",
    "Voir les billets",
    "Lose ansehen",
    "查看彩票",
    "チケットを見る",
    "티켓 보기",
  ],
  reviewPrize: [
    "Review prize",
    "Revisar premio",
    "Conferir prêmio",
    "Vérifier le gain",
    "Gewinn prüfen",
    "核实奖金",
    "賞金を確認",
    "당첨금 확인",
  ],
  verifiedReview: [
    "The review checks current ownership and the exact prize before you sign.",
    "La revisión verifica la titularidad actual y el premio exacto antes de firmar.",
    "A revisão verifica a posse atual e o prêmio exato antes de assinar.",
    "La vérification contrôle le détenteur actuel et le gain exact avant signature.",
    "Vor der Signatur werden aktueller Besitz und genauer Gewinn geprüft.",
    "签名前会核实当前持有权及确切奖金。",
    "署名前に現在の所有者と正確な賞金を確認します。",
    "서명 전에 현재 소유권과 정확한 당첨금을 확인합니다.",
  ],
  historyCoverage: [
    "Showing the {count} most recent draws. Older tickets are still available by draw number.",
    "Mostrando los {count} sorteos más recientes. Puedes consultar boletos anteriores por número de sorteo.",
    "Exibindo os {count} sorteios mais recentes. Consulte bilhetes anteriores pelo número do sorteio.",
    "Les {count} derniers tirages sont affichés. Retrouvez les billets plus anciens par numéro de tirage.",
    "Die letzten {count} Ziehungen. Ältere Lose lassen sich über die Ziehungsnummer aufrufen.",
    "显示最近 {count} 期开奖。可按期号查询更早的彩票。",
    "直近 {count} 回の抽選を表示。以前のチケットは抽選番号で検索できます。",
    "최근 {count}회 추첨입니다. 이전 티켓은 회차 번호로 조회할 수 있습니다.",
  ],
  olderDraw: [
    "Find an older draw",
    "Buscar un sorteo anterior",
    "Buscar sorteio anterior",
    "Trouver un ancien tirage",
    "Ältere Ziehung suchen",
    "查找更早期次",
    "以前の抽選を検索",
    "이전 회차 찾기",
  ],
  checking: [
    "Checking tickets…",
    "Consultando boletos…",
    "Consultando bilhetes…",
    "Recherche des billets…",
    "Lose werden geprüft…",
    "正在查询彩票…",
    "チケットを確認中…",
    "티켓 확인 중…",
  ],
  noTicketsShort: [
    "No tickets",
    "Sin boletos",
    "Sem bilhetes",
    "Aucun billet",
    "Keine Lose",
    "没有彩票",
    "チケットなし",
    "티켓 없음",
  ],
  unavailable: [
    "Could not check",
    "No se pudo consultar",
    "Não foi possível consultar",
    "Vérification impossible",
    "Abfrage fehlgeschlagen",
    "暂时无法查询",
    "確認できませんでした",
    "확인할 수 없음",
  ],
  balance: [
    "Balance",
    "Saldo",
    "Saldo",
    "Solde",
    "Guthaben",
    "余额",
    "残高",
    "잔액",
  ],
  inWallet: [
    "In your wallet",
    "En tu cartera",
    "Na sua carteira",
    "Dans votre portefeuille",
    "In deiner Wallet",
    "钱包中",
    "ウォレット内",
    "내 지갑에 보유",
  ],
  onBase: [
    "USDC on Base",
    "USDC en Base",
    "USDC na Base",
    "USDC sur Base",
    "USDC auf Base",
    "Base 上的 USDC",
    "Base の USDC",
    "Base의 USDC",
  ],
  balanceConnect: [
    "Connect to see your balance",
    "Conecta para ver tu saldo",
    "Conecte para ver seu saldo",
    "Connectez-vous pour voir votre solde",
    "Wallet verbinden und Guthaben sehen",
    "连接钱包查看余额",
    "接続して残高を確認",
    "연결하여 잔액 확인",
  ],
  earnings: [
    "Your winnings",
    "Tus premios",
    "Seus prêmios",
    "Vos gains",
    "Deine Gewinne",
    "您的奖金",
    "あなたの賞金",
    "내 당첨금",
  ],
  earningsHelp: [
    "Open a past draw, then choose a ticket to check its prize. Club carries the ticket ID into your review.",
    "Abre un sorteo anterior y elige un boleto para consultar su premio. Club lleva el ID a la revisión.",
    "Abra um sorteio anterior e escolha um bilhete para conferir o prêmio. Club leva o ID à revisão.",
    "Ouvrez un tirage passé et choisissez un billet. Club transmet son identifiant à la vérification du gain.",
    "Öffne eine vergangene Ziehung und wähle ein Los. Club übernimmt die Los-ID für die Gewinnprüfung.",
    "打开往期开奖，选择彩票核实奖金。Club 会自动填入彩票编号。",
    "過去の抽選からチケットを選ぶと、賞金確認にIDが自動入力されます。",
    "지난 추첨에서 티켓을 선택하면 당첨금 확인에 ID가 자동으로 입력됩니다.",
  ],
  findPrizes: [
    "Check my past tickets",
    "Consultar mis boletos anteriores",
    "Conferir meus bilhetes anteriores",
    "Consulter mes anciens billets",
    "Meine früheren Lose prüfen",
    "查看我的往期彩票",
    "過去のチケットを確認",
    "지난 티켓 확인",
  ],
  referralEarnings: [
    "Referral earnings",
    "Ganancias por invitaciones",
    "Ganhos por indicações",
    "Gains de parrainage",
    "Empfehlungsprämien",
    "推荐奖励",
    "紹介報酬",
    "추천 수익",
  ],
  noReferrals: [
    "No referral earnings to claim.",
    "No hay ganancias por invitaciones para reclamar.",
    "Nenhum ganho por indicação a resgatar.",
    "Aucun gain de parrainage à réclamer.",
    "Keine Empfehlungsprämien zur Auszahlung.",
    "暂无可领取的推荐奖励。",
    "受け取れる紹介報酬はありません。",
    "청구할 추천 수익이 없습니다.",
  ],
  lookupReady: [
    "Ticket ready to review",
    "Boleto listo para revisar",
    "Bilhete pronto para conferir",
    "Billet prêt à vérifier",
    "Los zur Prüfung bereit",
    "彩票已准备好核实",
    "チケットを確認できます",
    "확인할 티켓이 준비됨",
  ],
  lastKnown: [
    "Last known balance · refresh to update",
    "Último saldo conocido · actualiza para renovarlo",
    "Último saldo conhecido · atualize para renovar",
    "Dernier solde connu · actualisez pour le mettre à jour",
    "Zuletzt bekanntes Guthaben · bitte aktualisieren",
    "上次已知余额 · 请刷新",
    "前回の残高 · 更新してください",
    "마지막 잔액 · 새로고침하세요",
  ],
  localStale: [
    "Last known balance · refresh failed",
    "Último saldo conocido · error al actualizar",
    "Último saldo conhecido · falha na atualização",
    "Dernier solde connu · actualisation échouée",
    "Zuletzt bekanntes Guthaben · Aktualisierung fehlgeschlagen",
    "上次已知余额 · 刷新失败",
    "前回の残高 · 更新に失敗",
    "마지막 잔액 · 새로고침 실패",
  ],
} as const satisfies Record<
  string,
  readonly [string, string, string, string, string, string, string, string]
>;
export const experienceKeys = Object.keys(words) as (keyof typeof words)[];
export function experienceCopy(locale: Locale) {
  const index = LANGUAGES.findIndex((l) => l.code === locale);
  return (key: keyof typeof words) => words[key][index];
}
