import { LANGUAGES, type Locale } from "./i18n.ts";
const words = {
  resetWallet: [
    "Reset connection",
    "Restablecer conexión",
    "Redefinir conexão",
    "Réinitialiser la connexion",
    "Verbindung zurücksetzen",
    "重置连接",
    "接続をリセット",
    "연결 재설정",
  ],
  restoreSlow: [
    "Wallet not responding? Reload without restoring it to connect again.",
    "¿La cartera no responde? Recarga sin restaurarla para volver a conectar.",
    "A carteira não responde? Recarregue sem restaurá-la para conectar novamente.",
    "Le portefeuille ne répond pas ? Rechargez sans le restaurer pour vous reconnecter.",
    "Wallet reagiert nicht? Ohne Wiederherstellung neu laden und erneut verbinden.",
    "钱包无响应？重新加载并跳过恢复，然后重新连接。",
    "ウォレットが応答しない場合は、復元せずに再読み込みして接続し直せます。",
    "지갑이 응답하지 않나요? 복원 없이 새로고침한 후 다시 연결하세요.",
  ],
  restoring: [
    "Restoring wallet…",
    "Restaurando cartera…",
    "Restaurando carteira…",
    "Restauration du portefeuille…",
    "Wallet wird wiederhergestellt…",
    "正在恢复钱包…",
    "ウォレットを復元中…",
    "지갑 복원 중…",
  ],
  viewingAddress: [
    "Viewing",
    "Consultando",
    "Consultando",
    "Adresse consultée",
    "Angezeigte Adresse",
    "正在查看",
    "表示中",
    "조회 중",
  ],
  connectedWallet: [
    "Your wallet",
    "Tu cartera",
    "Sua carteira",
    "Votre portefeuille",
    "Deine Wallet",
    "您的钱包",
    "あなたのウォレット",
    "내 지갑",
  ],
  connectHint: [
    "Your tickets on Base",
    "Tus boletos en Base",
    "Seus bilhetes na Base",
    "Vos billets sur Base",
    "Deine Lose auf Base",
    "您在 Base 上的彩票",
    "Base のあなたのチケット",
    "Base의 내 티켓",
  ],
  anotherAddress: [
    "Look up an address",
    "Consultar una dirección",
    "Consultar um endereço",
    "Consulter une adresse",
    "Adresse nachschlagen",
    "查询地址",
    "アドレスを検索",
    "주소 조회",
  ],
  publicLinkNote: [
    "Public lookups include the address in this page’s URL. No wallet connection needed.",
    "Las consultas públicas incluyen la dirección en la URL. No necesitas conectar una cartera.",
    "Consultas públicas incluem o endereço na URL. Não é preciso conectar uma carteira.",
    "L’adresse consultée figure dans l’URL. Aucune connexion de portefeuille nécessaire.",
    "Bei öffentlichen Abfragen steht die Adresse in der URL. Keine Wallet-Verbindung nötig.",
    "公开查询会在页面链接中包含地址，无需连接钱包。",
    "公開検索ではアドレスがページのURLに含まれます。ウォレット接続は不要です。",
    "공개 조회 시 페이지 URL에 주소가 포함됩니다. 지갑 연결은 필요하지 않습니다.",
  ],
  browseDraws: [
    "Browse drawings",
    "Explorar sorteos",
    "Explorar sorteios",
    "Parcourir les tirages",
    "Ziehungen durchsehen",
    "浏览开奖",
    "抽選を閲覧",
    "회차 탐색",
  ],
  previousDraw: [
    "Previous draw",
    "Sorteo anterior",
    "Sorteio anterior",
    "Tirage précédent",
    "Vorherige Ziehung",
    "上一期",
    "前の抽選",
    "이전 회차",
  ],
  nextDraw: [
    "Next draw",
    "Siguiente sorteo",
    "Próximo sorteio",
    "Tirage suivant",
    "Nächste Ziehung",
    "下一期",
    "次の抽選",
    "다음 회차",
  ],
  refresh: [
    "Refresh",
    "Actualizar",
    "Atualizar",
    "Actualiser",
    "Aktualisieren",
    "刷新",
    "更新",
    "새로고침",
  ],
  connectTitle: [
    "See your tickets.",
    "Mira tus boletos.",
    "Veja seus bilhetes.",
    "Retrouvez vos billets.",
    "Deine Lose ansehen.",
    "查看您的彩票。",
    "あなたのチケットを確認。",
    "내 티켓을 확인하세요.",
  ],
  connectDetail: [
    "Connect your wallet to see its tickets automatically. Then move between draws without entering an address.",
    "Conecta tu cartera para ver sus boletos automáticamente y explorar sorteos sin introducir una dirección.",
    "Conecte sua carteira para ver os bilhetes automaticamente e navegar entre sorteios sem digitar um endereço.",
    "Connectez votre portefeuille pour afficher ses billets, puis passez d’un tirage à l’autre sans saisir d’adresse.",
    "Verbinde deine Wallet. Deine Lose erscheinen automatisch, und du wechselst ohne Adresseingabe zwischen Ziehungen.",
    "连接钱包即可自动查看彩票，并切换查看不同期次，无需输入地址。",
    "ウォレットを接続するとチケットが自動表示されます。アドレスを入力せずに抽選を切り替えられます。",
    "지갑을 연결하면 티켓이 자동으로 표시됩니다. 주소 입력 없이 회차를 바꿔 볼 수 있습니다.",
  ],
  readOnly: [
    "Read-only · No signature to view tickets",
    "Solo lectura · Sin firma para ver boletos",
    "Somente leitura · Sem assinatura para ver bilhetes",
    "Lecture seule · Aucune signature pour consulter",
    "Nur Lesen · Keine Signatur zum Ansehen",
    "只读查询 · 查看彩票无需签名",
    "読み取り専用 · 閲覧に署名は不要",
    "읽기 전용 · 티켓 조회에 서명 불필요",
  ],
  readFailed: [
    "Tickets could not be refreshed.",
    "No se pudieron actualizar los boletos.",
    "Não foi possível atualizar os bilhetes.",
    "Les billets n’ont pas pu être actualisés.",
    "Lose konnten nicht aktualisiert werden.",
    "无法刷新彩票。",
    "チケットを更新できませんでした。",
    "티켓을 새로고침하지 못했습니다.",
  ],
  keptResults: [
    "Your last successful result is still here. It may be out of date.",
    "Se conserva la última consulta correcta. Puede estar desactualizada.",
    "O último resultado válido continua aqui. Pode estar desatualizado.",
    "Le dernier résultat valide reste affiché. Il peut être ancien.",
    "Das letzte erfolgreiche Ergebnis bleibt sichtbar. Es kann veraltet sein.",
    "仍显示上次成功查询的结果，数据可能已过期。",
    "前回取得できた結果を表示しています。最新ではない可能性があります。",
    "마지막으로 조회한 결과를 유지합니다. 최신 정보가 아닐 수 있습니다.",
  ],
  retryHelp: [
    "This is a connection problem, not an empty collection. Try again or check connection settings.",
    "Es un problema de conexión, no una colección vacía. Reintenta o revisa los ajustes.",
    "É um problema de conexão, não uma coleção vazia. Tente novamente ou confira as configurações.",
    "Il s’agit d’un problème de connexion, pas d’une collection vide. Réessayez ou vérifiez les paramètres.",
    "Es liegt ein Verbindungsproblem vor; deine Sammlung ist nicht unbedingt leer. Erneut versuchen oder Einstellungen prüfen.",
    "这是连接问题，并不代表您没有彩票。请重试或检查连接设置。",
    "接続の問題です。チケットがないという意味ではありません。再試行するか接続設定を確認してください。",
    "연결 문제이며, 티켓이 없다는 뜻은 아닙니다. 다시 시도하거나 연결 설정을 확인하세요.",
  ],
  retry: [
    "Try again",
    "Reintentar",
    "Tentar novamente",
    "Réessayer",
    "Erneut versuchen",
    "重试",
    "再試行",
    "다시 시도",
  ],
  loading: [
    "Finding your tickets…",
    "Buscando tus boletos…",
    "Buscando seus bilhetes…",
    "Recherche de vos billets…",
    "Deine Lose werden geladen…",
    "正在查找彩票…",
    "チケットを検索中…",
    "티켓을 찾는 중…",
  ],
  oneTicket: [
    "1 ticket",
    "1 boleto",
    "1 bilhete",
    "1 billet",
    "1 Los",
    "1 张彩票",
    "1 枚のチケット",
    "티켓 1장",
  ],
  noTickets: [
    "No tickets in this draw.",
    "No hay boletos en este sorteo.",
    "Nenhum bilhete neste sorteio.",
    "Aucun billet pour ce tirage.",
    "Keine Lose für diese Ziehung.",
    "本期没有彩票。",
    "この抽選のチケットはありません。",
    "이 회차에 티켓이 없습니다.",
  ],
  noTicketsHelp: [
    "This address holds no tickets for the selected draw. If you played earlier, try a previous draw.",
    "Esta dirección no tiene boletos del sorteo seleccionado. Si participaste antes, consulta un sorteo anterior.",
    "Este endereço não tem bilhetes no sorteio selecionado. Se participou antes, confira um sorteio anterior.",
    "Cette adresse ne détient aucun billet pour ce tirage. Si vous avez joué plus tôt, consultez un tirage précédent.",
    "Diese Adresse hält keine Lose der gewählten Ziehung. Hast du früher gespielt, sieh bei einer früheren Ziehung nach.",
    "此地址未持有所选期次的彩票。如果您之前参与过，请查看往期。",
    "このアドレスは選択した抽選のチケットを保有していません。以前に参加した場合は前の抽選をご確認ください。",
    "이 주소는 선택한 회차의 티켓을 보유하고 있지 않습니다. 이전에 참여했다면 이전 회차를 확인하세요.",
  ],
  matchHelp: [
    "Matching numbers are marked. Prize eligibility is checked separately at review.",
    "Los números coincidentes están marcados. El derecho a premio se verifica al revisar.",
    "Números coincidentes estão marcados. A elegibilidade ao prêmio é verificada na revisão.",
    "Les numéros correspondants sont marqués. Le droit au gain est vérifié séparément.",
    "Treffer sind markiert. Der Gewinnanspruch wird bei der Prüfung gesondert ermittelt.",
    "已标记匹配号码。领奖资格将在核实时单独确认。",
    "一致する番号に印が付きます。受取資格は確認時に別途検証します。",
    "일치하는 번호가 표시됩니다. 당첨금 수령 자격은 검토 시 별도로 확인합니다.",
  ],
  matched: [
    "Match",
    "Coincide",
    "Coincide",
    "Correspondance",
    "Treffer",
    "匹配",
    "一致",
    "일치",
  ],
  mainMatches: [
    "{count} main matches",
    "{count} coincidencias principales",
    "{count} números principais coincidentes",
    "{count} numéros principaux correspondants",
    "{count} Hauptzahlen stimmen überein",
    "{count} 个主号码匹配",
    "メイン番号 {count} 個一致",
    "주 번호 {count}개 일치",
  ],
  bonusMatched: [
    "Bonus matched",
    "Bono acertado",
    "Bônus coincidente",
    "Bonus correspondant",
    "Bonus stimmt überein",
    "特别号码匹配",
    "ボーナス一致",
    "보너스 일치",
  ],
  recorded: [
    "Recorded on Base",
    "Registrado en Base",
    "Registrado na Base",
    "Enregistré sur Base",
    "Auf Base erfasst",
    "已记录于 Base",
    "Base に記録済み",
    "Base에 기록됨",
  ],
  pageOf: [
    "{page} of {pages}",
    "{page} de {pages}",
    "{page} de {pages}",
    "{page} sur {pages}",
    "{page} von {pages}",
    "第 {page} 页，共 {pages} 页",
    "{page} / {pages}",
    "{page} / {pages}",
  ],
  previousPage: [
    "Previous",
    "Anterior",
    "Anterior",
    "Précédent",
    "Zurück",
    "上一页",
    "前へ",
    "이전",
  ],
  nextPage: [
    "Next",
    "Siguiente",
    "Próxima",
    "Suivant",
    "Weiter",
    "下一页",
    "次へ",
    "다음",
  ],
  ticketPages: [
    "Ticket pages",
    "Páginas de boletos",
    "Páginas de bilhetes",
    "Pages de billets",
    "Losseiten",
    "彩票分页",
    "チケットのページ",
    "티켓 페이지",
  ],
  share: [
    "Copy view link",
    "Copiar enlace",
    "Copiar link",
    "Copier le lien",
    "Ansichtslink kopieren",
    "复制查看链接",
    "表示リンクをコピー",
    "조회 링크 복사",
  ],
} as const satisfies Record<
  string,
  readonly [string, string, string, string, string, string, string, string]
>;
export const ticketKeys = Object.keys(words) as (keyof typeof words)[];
export function ticketCopy(locale: Locale) {
  const index = LANGUAGES.findIndex((l) => l.code === locale);
  return (key: keyof typeof words) => words[key][index];
}
