import type { Locale } from "./i18n.ts";
const locales: Locale[] = [
  "en",
  "es",
  "pt-BR",
  "fr",
  "de",
  "zh-CN",
  "ja",
  "ko",
];
const words = {
  defenseHelp: [
    "The strategy sells up to this amount of its own collateral to repay USDC debt. You pay network fees; this is not Ether taken from your wallet.",
    "La estrategia vende hasta esta cantidad de su propia garantía para pagar deuda USDC. Tú pagas la comisión de red; no se retira ese Ether de tu cartera.",
    "A estratégia vende até este valor da própria garantia para quitar dívida USDC. Você paga a taxa de rede; esse Ether não sai da sua carteira.",
    "La stratégie vend au maximum ce montant de sa propre garantie pour rembourser l’USDC. Vous payez les frais réseau ; cet Ether n’est pas prélevé sur votre portefeuille.",
    "Die Strategie verkauft bis zu dieser Menge ihrer eigenen Sicherheiten zur USDC-Tilgung. Sie zahlen Netzwerkgebühren; dieser Ether wird nicht Ihrer Wallet entnommen.",
    "策略最多出售这一数量的自有抵押品以偿还 USDC 债务。您支付网络费；不会从您的钱包取走这些 Ether。",
    "戦略自身の担保をこの上限まで売却してUSDC債務を返済します。負担するのはネットワーク手数料で、このEtherはウォレットから引き落とされません。",
    "전략 자체 담보를 이 한도까지 매도하여 USDC 부채를 상환합니다. 네트워크 수수료만 부담하며 이 Ether는 지갑에서 출금되지 않습니다.",
  ],
  receipt: [
    "Receipt shares",
    "Participaciones",
    "Cotas",
    "Parts",
    "Anteile",
    "凭证份额",
    "持分",
    "영수증 지분",
  ],
  position: [
    "Strategy position",
    "Posición de estrategia",
    "Posição da estratégia",
    "Position de stratégie",
    "Strategieposition",
    "策略头寸",
    "戦略ポジション",
    "전략 포지션",
  ],
  defend: [
    "Repay debt using collateral",
    "Pagar deuda con garantía",
    "Pagar dívida com garantia",
    "Rembourser avec la garantie",
    "Schulden mit Sicherheiten tilgen",
    "使用抵押品偿还债务",
    "担保で負債を返済",
    "담보로 부채 상환",
  ],
  maximum: [
    "Maximum Ether to sell",
    "Máximo Ether a vender",
    "Máximo de Ether a vender",
    "Ether maximal à vendre",
    "Maximal zu verkaufender Ether",
    "最多出售 Ether",
    "Ether売却上限",
    "최대 Ether 매도량",
  ],
  deposit: [
    "Deposit",
    "Depositar",
    "Depositar",
    "Déposer",
    "Einzahlen",
    "存款",
    "入金",
    "입금",
  ],
  withdraw: [
    "Request exit",
    "Solicitar salida",
    "Solicitar saída",
    "Demander une sortie",
    "Auszahlung anfordern",
    "请求退出",
    "出金申請",
    "출금 요청",
  ],
  amount: [
    "Amount",
    "Cantidad",
    "Valor",
    "Montant",
    "Betrag",
    "金额",
    "金額",
    "금액",
  ],
  wallet: [
    "Your wallet",
    "Tu cartera",
    "Sua carteira",
    "Votre portefeuille",
    "Ihre Wallet",
    "您的钱包",
    "ウォレット",
    "내 지갑",
  ],
  save: [
    "Save endpoints",
    "Guardar endpoints",
    "Salvar endpoints",
    "Enregistrer les points d’accès",
    "Endpunkte speichern",
    "保存端点",
    "エンドポイントを保存",
    "엔드포인트 저장",
  ],
  exitSteps: [
    "Request an exit for an exact number of shares. Completed withdrawals are claimed separately; returns depend on settlement.",
    "Solicita salir con un número exacto de participaciones. Los retiros completados se cobran por separado y dependen de la liquidación.",
    "Solicite a saída de um número exato de cotas. Saques concluídos são resgatados separadamente e dependem da liquidação.",
    "Demandez une sortie pour un nombre exact de parts. Les retraits réglés sont réclamés séparément ; leur retour dépend du règlement.",
    "Auszahlung einer exakten Anzahl von Anteilen anfordern. Abgerechnete Mittel werden separat abgeholt; die Rückzahlung hängt von der Abrechnung ab.",
    "以确切份额数量请求退出。完成结算的提现需单独领取，返还取决于结算。",
    "正確な持分数で出金を申請します。決済済み資金は別途受け取り、返還は決済状況に依存します。",
    "정확한 지분 수로 출금을 요청하세요. 정산된 출금은 별도로 수령하며 반환은 정산에 달려 있습니다.",
  ],
  spender: [
    "Authorized spender",
    "Contrato autorizado",
    "Contrato autorizado",
    "Contrat autorisé",
    "Freigegebener Spender",
    "获授权支出合约",
    "承認する支出先",
    "승인된 지출 계약",
  ],
  shared: [
    "A shared position. Your own shares.",
    "Una posición compartida. Tus propias participaciones.",
    "Uma posição compartilhada. Suas próprias cotas.",
    "Une position commune. Vos propres parts.",
    "Gemeinsame Position. Eigene Anteile.",
    "共享头寸，独立份额。",
    "共有ポジション。あなた自身の持分。",
    "공동 포지션, 나만의 지분.",
  ],
  usdcStory: [
    "USDC earns Aave supply yield while waiting for pool capacity. Accepted deposits receive transferable shares; exits follow the pool’s draw cycle.",
    "USDC genera rendimiento en Aave mientras espera capacidad. Los depósitos aceptados reciben participaciones transferibles; las salidas siguen el ciclo de sorteos.",
    "USDC rende no Aave enquanto aguarda capacidade. Depósitos aceitos recebem cotas transferíveis; saídas seguem o ciclo dos sorteios.",
    "L’USDC produit un rendement Aave en attendant une place. Les dépôts acceptés reçoivent des parts transférables ; les sorties suivent les tirages.",
    "USDC erzielt während der Wartezeit Aave-Zinsen. Angenommene Einzahlungen erhalten übertragbare Anteile; Auszahlungen folgen dem Ziehungszyklus.",
    "等待奖池容量时，USDC 在 Aave 获得供应收益。接纳存款后获得可转让份额，退出遵循开奖周期。",
    "受入枠を待つUSDCはAaveで供給利息を得ます。受入後は譲渡可能な持分を取得し、出金は抽選サイクルに従います。",
    "대기 중 USDC는 Aave 공급 수익을 얻습니다. 수락된 입금은 양도 가능한 지분을 받고 출금은 추첨 주기를 따릅니다.",
  ],
  ethStory: [
    "Ether supplies collateral for USDC borrowing. Entries and exits are priced only after the shared strategy fully unwinds and repays its debt.",
    "Ether respalda préstamos de USDC. Entradas y salidas se valoran solo tras deshacer toda la estrategia y pagar la deuda.",
    "Ether garante empréstimos de USDC. Entradas e saídas são precificadas após encerrar a estratégia e quitar a dívida.",
    "L’Ether garantit des emprunts USDC. Entrées et sorties sont valorisées après liquidation de la stratégie et remboursement de sa dette.",
    "Ether besichert USDC-Kredite. Ein- und Auszahlungen werden erst nach vollständiger Abwicklung und Schuldentilgung bewertet.",
    "Ether 用作借入 USDC 的抵押品。共享策略完全退出并偿还债务后，才为存入和退出定价。",
    "Etherを担保にUSDCを借り入れます。共有戦略を完全に解消し負債を返済した後に、入出金を評価します。",
    "Ether를 담보로 USDC를 빌립니다. 공동 전략을 완전히 청산하고 부채를 갚은 후에만 입출금 가격이 결정됩니다.",
  ],
  bridgeStory: [
    "Funds travel to Base through CCTP. Returns wait for authenticated messages and the actual USDC mint on Ethereum.",
    "Los fondos viajan a Base por CCTP. El retorno espera mensajes autenticados y la emisión real de USDC en Ethereum.",
    "Os fundos vão à Base por CCTP. O retorno aguarda mensagens autenticadas e a emissão real de USDC no Ethereum.",
    "Les fonds rejoignent Base via CCTP. Le retour attend les messages authentifiés et l’émission effective d’USDC sur Ethereum.",
    "Mittel gelangen per CCTP zu Base. Rückzahlungen warten auf authentifizierte Nachrichten und die tatsächliche USDC-Ausgabe auf Ethereum.",
    "资金通过 CCTP 转至 Base。返还须等待认证消息及以太坊上实际铸造的 USDC。",
    "資金はCCTPでBaseへ移動します。返還には認証済みメッセージとEthereum上の実際のUSDC発行を待ちます。",
    "자금은 CCTP로 Base에 이동합니다. 반환은 인증된 메시지와 Ethereum의 실제 USDC 발행을 기다립니다.",
  ],
  risks: [
    "Pool losses can reduce your balance. Ether strategies also carry borrowing and liquidation risk. Withdrawals depend on pool, lending and bridge liquidity; timing is not guaranteed.",
    "Las pérdidas pueden reducir tu saldo. Ether añade riesgo de deuda y liquidación. Los retiros dependen de la liquidez del pool, préstamo y puente; el plazo no está garantizado.",
    "Perdas podem reduzir seu saldo. Ether também envolve dívida e liquidação. Saques dependem da liquidez do pool, empréstimo e ponte; o prazo não é garantido.",
    "Les pertes peuvent réduire votre solde. L’Ether comporte aussi des risques de dette et liquidation. Les délais dépendent des liquidités du pool, des prêts et du pont et ne sont pas garantis.",
    "Pool-Verluste können das Guthaben mindern. Ether-Strategien haben zudem Kredit- und Liquidationsrisiken. Auszahlungen hängen von Pool-, Kredit- und Bridge-Liquidität ab; kein garantierter Termin.",
    "奖池亏损可能减少余额。Ether 策略还有借贷和清算风险。提现取决于奖池、借贷及跨链流动性，时间不保证。",
    "プールの損失で残高が減る場合があります。Ether戦略には借入・清算リスクもあります。出金時期はプール、貸付、ブリッジの流動性に依存し、保証されません。",
    "풀 손실로 잔액이 줄 수 있습니다. Ether 전략에는 차입과 청산 위험도 있습니다. 출금 시점은 풀, 대출, 브리지 유동성에 달려 있으며 보장되지 않습니다.",
  ],
  launch: [
    "These vaults are not deployed yet. You can explore the complete workflow; deposits open once verified contracts are configured.",
    "Estas bóvedas aún no están desplegadas. Explora el flujo completo; los depósitos se abrirán con contratos verificados.",
    "Estes cofres ainda não foram implantados. Explore o fluxo completo; depósitos serão abertos com contratos verificados.",
    "Ces coffres ne sont pas encore déployés. Explorez leur parcours ; les dépôts ouvriront avec des contrats vérifiés.",
    "Diese Vaults sind noch nicht bereitgestellt. Der gesamte Ablauf ist einsehbar; Einzahlungen öffnen nach Einrichtung verifizierter Verträge.",
    "这些金库尚未部署。您可以查看完整流程；配置已验证合约后开放存款。",
    "これらのボールトは未デプロイです。全体の流れを確認できます。検証済みコントラクトの設定後に入金可能になります。",
    "아직 배포되지 않은 금고입니다. 전체 흐름을 살펴볼 수 있으며 검증된 계약이 설정되면 입금이 열립니다.",
  ],
  requests: [
    "Requests",
    "Solicitudes",
    "Solicitações",
    "Demandes",
    "Anfragen",
    "请求",
    "リクエスト",
    "요청",
  ],
  manage: [
    "Progress & recovery",
    "Progreso y recuperación",
    "Progresso e recuperação",
    "Progression et récupération",
    "Fortschritt und Wiederherstellung",
    "推进与恢复",
    "進行・復旧",
    "진행 및 복구",
  ],
  requestId: [
    "Request ID",
    "ID de solicitud",
    "ID da solicitação",
    "Identifiant de demande",
    "Anfrage-ID",
    "请求 ID",
    "リクエストID",
    "요청 ID",
  ],
  requestKind: [
    "Request type",
    "Tipo de solicitud",
    "Tipo de solicitação",
    "Type de demande",
    "Anfragetyp",
    "请求类型",
    "リクエストの種類",
    "요청 유형",
  ],
  lookup: [
    "Open request",
    "Abrir solicitud",
    "Abrir solicitação",
    "Ouvrir la demande",
    "Anfrage öffnen",
    "打开请求",
    "リクエストを開く",
    "요청 열기",
  ],
  exactShares: [
    "Exact receipt shares",
    "Participaciones exactas",
    "Cotas exatas",
    "Parts exactes",
    "Exakte Anteile",
    "确切凭证份额",
    "正確な持分数",
    "정확한 영수증 지분",
  ],
  owner: [
    "Owner",
    "Titular",
    "Titular",
    "Titulaire",
    "Eigentümer",
    "所有者",
    "所有者",
    "소유자",
  ],
  draft: [
    "Draft saved on this device",
    "Borrador guardado en este dispositivo",
    "Rascunho salvo neste dispositivo",
    "Brouillon enregistré sur cet appareil",
    "Entwurf auf diesem Gerät gespeichert",
    "草稿已保存在此设备",
    "この端末に下書きを保存",
    "이 기기에 초안 저장됨",
  ],
  wrapped: [
    "Your Ether is wrapped into WETH within the deposit. Claims try Ether first and deliver WETH if your recipient cannot receive Ether.",
    "Tu Ether se envuelve como WETH al depositar. Los cobros intentan entregar Ether y usan WETH si el destinatario no puede recibirlo.",
    "Seu Ether é convertido em WETH no depósito. Resgates tentam Ether e entregam WETH se o destinatário não puder recebê-lo.",
    "Votre Ether est enveloppé en WETH lors du dépôt. Les retraits livrent de l’Ether, ou du WETH si le destinataire ne peut pas recevoir d’Ether.",
    "Ether wird bei der Einzahlung in WETH umgewandelt. Auszahlungen versuchen Ether und liefern bei nicht empfangsfähiger Adresse WETH.",
    "存款时 Ether 自动包装为 WETH。领取时优先发送 Ether；收款方无法接收时发送 WETH。",
    "入金時にEtherをWETHへ変換します。受取時はEtherを優先し、受取先が対応しない場合はWETHを送ります。",
    "입금 시 Ether가 WETH로 래핑됩니다. 수령 시 Ether를 우선 전송하고 받을 수 없으면 WETH로 전달합니다.",
  ],
  approvalStep: [
    "First authorize this exact USDC amount. After confirmation, review the deposit separately.",
    "Primero autoriza esta cantidad exacta de USDC. Tras confirmarse, revisa el depósito por separado.",
    "Primeiro autorize este valor exato de USDC. Após confirmar, revise o depósito separadamente.",
    "Autorisez d’abord ce montant exact d’USDC. Après confirmation, examinez séparément le dépôt.",
    "Zuerst diesen exakten USDC-Betrag freigeben. Danach die Einzahlung separat prüfen.",
    "先授权这笔确切 USDC 金额。确认后单独审核存款。",
    "まずこの正確なUSDC額を承認します。確認後に入金を別途レビューしてください。",
    "먼저 정확한 USDC 금액을 승인하세요. 확인 후 입금을 별도로 검토하세요.",
  ],
  reviewDraft: [
    "Deposit workflow",
    "Flujo de depósito",
    "Fluxo de depósito",
    "Parcours de dépôt",
    "Einzahlungsablauf",
    "存款流程",
    "入金の流れ",
    "입금 흐름",
  ],
  due: [
    "Sent with this transaction",
    "Enviado con esta transacción",
    "Enviado nesta transação",
    "Envoyé avec cette transaction",
    "Mit dieser Transaktion gesendet",
    "此交易发送金额",
    "この取引で送る額",
    "이 거래로 보내는 금액",
  ],
  rpc: [
    "Ethereum RPC endpoints",
    "Endpoints RPC de Ethereum",
    "Endpoints RPC do Ethereum",
    "Points RPC Ethereum",
    "Ethereum-RPC-Endpunkte",
    "以太坊 RPC 端点",
    "Ethereum RPCエンドポイント",
    "Ethereum RPC 엔드포인트",
  ],
  rpcHelp: [
    "One HTTPS endpoint per line. Kept on this device; never included in shared links.",
    "Un endpoint HTTPS por línea. Se guarda en este dispositivo; nunca en enlaces compartidos.",
    "Um endpoint HTTPS por linha. Salvo neste dispositivo, nunca em links compartilhados.",
    "Un point HTTPS par ligne. Conservé sur cet appareil, jamais dans les liens partagés.",
    "Ein HTTPS-Endpunkt je Zeile. Nur auf diesem Gerät gespeichert, nie in geteilten Links.",
    "每行一个 HTTPS 端点。仅保存在此设备，不包含在分享链接中。",
    "1行に1つのHTTPSエンドポイント。この端末にのみ保存し、共有リンクには含めません。",
    "줄마다 HTTPS 엔드포인트 하나. 이 기기에만 저장하며 공유 링크에 포함하지 않습니다.",
  ],
  cancelWaiting: [
    "Cancel waiting deposit",
    "Cancelar depósito en espera",
    "Cancelar depósito em espera",
    "Annuler le dépôt en attente",
    "Wartende Einzahlung stornieren",
    "取消等待存款",
    "待機中の入金を取消",
    "대기 입금 취소",
  ],
  claimWaiting: [
    "Recover waiting funds",
    "Recuperar fondos en espera",
    "Recuperar fundos em espera",
    "Récupérer les fonds en attente",
    "Wartende Mittel abheben",
    "取回等待资金",
    "待機資金を回収",
    "대기 자금 회수",
  ],
  claimLender: [
    "Receive Aave tokens",
    "Recibir tokens Aave",
    "Receber tokens Aave",
    "Recevoir les tokens Aave",
    "Aave-Token erhalten",
    "接收 Aave 代币",
    "Aaveトークンを受取",
    "Aave 토큰 받기",
  ],
  claimReceipt: [
    "Collect earned shares",
    "Cobrar participaciones",
    "Receber cotas adquiridas",
    "Recevoir les parts acquises",
    "Erworbene Anteile abholen",
    "领取已获得份额",
    "獲得済み持分を受取",
    "획득한 지분 수령",
  ],
  claimCash: [
    "Collect available funds",
    "Cobrar fondos disponibles",
    "Receber fundos disponíveis",
    "Recevoir les fonds disponibles",
    "Verfügbare Mittel abholen",
    "领取可用资金",
    "利用可能な資金を受取",
    "사용 가능한 자금 수령",
  ],
  cancelExit: [
    "Cancel unaccepted exit",
    "Cancelar salida no aceptada",
    "Cancelar saída não aceita",
    "Annuler la sortie non acceptée",
    "Nicht angenommene Auszahlung stornieren",
    "取消尚未接纳的退出",
    "未受理の出金を取消",
    "미수락 출금 취소",
  ],
  bridge: [
    "Send deposit to Base",
    "Enviar depósito a Base",
    "Enviar depósito à Base",
    "Envoyer le dépôt vers Base",
    "Einzahlung an Base senden",
    "将存款发送到 Base",
    "入金をBaseへ送る",
    "입금을 Base로 보내기",
  ],
  exitRemote: [
    "Request return to Ethereum",
    "Solicitar retorno a Ethereum",
    "Solicitar retorno ao Ethereum",
    "Demander le retour vers Ethereum",
    "Rückkehr zu Ethereum anfordern",
    "请求退回以太坊",
    "Ethereumへの返還を申請",
    "Ethereum으로 반환 요청",
  ],
  closeRequest: [
    "Complete request",
    "Completar solicitud",
    "Concluir solicitação",
    "Terminer la demande",
    "Anfrage abschließen",
    "完成请求",
    "リクエストを完了",
    "요청 완료",
  ],
  lot: [
    "Claim lot ID",
    "ID de lote a cobrar",
    "ID do lote de resgate",
    "Identifiant du lot à réclamer",
    "Anspruchslos-ID",
    "领取批次 ID",
    "請求ロットID",
    "청구 로트 ID",
  ],
  transfer: [
    "Transfer shares",
    "Transferir participaciones",
    "Transferir cotas",
    "Transférer les parts",
    "Anteile übertragen",
    "转让份额",
    "持分を送る",
    "지분 전송",
  ],
  recipient: [
    "Recipient address",
    "Dirección destinataria",
    "Endereço destinatário",
    "Adresse destinataire",
    "Empfängeradresse",
    "接收地址",
    "受取先アドレス",
    "수신 주소",
  ],
  history: [
    "On-chain requests",
    "Solicitudes en cadena",
    "Solicitações on-chain",
    "Demandes sur la chaîne",
    "Anfragen auf der Blockchain",
    "链上请求",
    "オンチェーンのリクエスト",
    "온체인 요청",
  ],
  older: [
    "Scan earlier blocks",
    "Consultar bloques anteriores",
    "Consultar blocos anteriores",
    "Rechercher les blocs précédents",
    "Frühere Blöcke durchsuchen",
    "扫描更早区块",
    "以前のブロックを検索",
    "이전 블록 검색",
  ],
  coverage: [
    "Scanned blocks",
    "Bloques consultados",
    "Blocos consultados",
    "Blocs consultés",
    "Durchsuchte Blöcke",
    "已扫描区块",
    "検索済みブロック",
    "조회한 블록",
  ],
  noHistory: [
    "No matching events in this range.",
    "Sin eventos en este rango.",
    "Nenhum evento neste intervalo.",
    "Aucun événement dans cet intervalle.",
    "Keine Ereignisse in diesem Bereich.",
    "此范围内无匹配事件。",
    "この範囲に該当イベントはありません。",
    "이 범위에 일치하는 이벤트가 없습니다.",
  ],
  progressHelp: [
    "These calls advance shared work. They do not run automatically; each requires your review and gas. A failed simulation leaves funds unchanged.",
    "Estas llamadas avanzan trabajo compartido. No son automáticas: requieren revisión y gas. Una simulación fallida no mueve fondos.",
    "Estas chamadas avançam o trabalho comum. Não são automáticas: exigem revisão e gas. Simulações falhas não movem fundos.",
    "Ces appels font progresser le travail commun. Chacun demande votre examen et du gas. Une simulation échouée ne déplace aucun fonds.",
    "Diese Aufrufe bringen gemeinsame Arbeit voran. Jeder erfordert Prüfung und Gas. Eine fehlgeschlagene Simulation bewegt keine Mittel.",
    "这些调用推进共享流程，不会自动运行；每次均需审核和 Gas。模拟失败不会移动资金。",
    "共有処理を進める操作です。自動ではなく、毎回確認とガスが必要です。シミュレーション失敗で資金は移動しません。",
    "공동 작업을 진행하는 호출입니다. 자동 실행되지 않으며 매번 검토와 가스가 필요합니다. 시뮬레이션 실패로 자금이 이동하지 않습니다.",
  ],
  waiting: [
    "Waiting",
    "En espera",
    "Em espera",
    "En attente",
    "Wartend",
    "等待中",
    "待機中",
    "대기 중",
  ],
  running: [
    "Open",
    "Abierto",
    "Aberto",
    "Ouvert",
    "Offen",
    "开放",
    "受付中",
    "열림",
  ],
  draining: [
    "Realizing the strategy",
    "Cerrando la estrategia",
    "Encerrando a estratégia",
    "Réalisation de la stratégie",
    "Strategie wird abgewickelt",
    "正在退出策略",
    "戦略を解消中",
    "전략 청산 중",
  ],
  stopped: [
    "Stopped · recovery available",
    "Detenido · recuperación disponible",
    "Parado · recuperação disponível",
    "Arrêté · récupération disponible",
    "Gestoppt · Rückgewinnung möglich",
    "已停止 · 可恢复",
    "停止・回収可能",
    "중지됨 · 복구 가능",
  ],
  debt: [
    "Shared USDC debt",
    "Deuda USDC compartida",
    "Dívida USDC compartilhada",
    "Dette USDC commune",
    "Gemeinsame USDC-Schuld",
    "共享 USDC 债务",
    "共有USDC負債",
    "공동 USDC 부채",
  ],
  batch: [
    "Settlement batch",
    "Lote de liquidación",
    "Lote de liquidação",
    "Lot de règlement",
    "Abrechnungsrunde",
    "结算批次",
    "決済バッチ",
    "정산 배치",
  ],
  inspect: [
    "Exact contract data",
    "Datos exactos del contrato",
    "Dados exatos do contrato",
    "Données exactes du contrat",
    "Exakte Vertragsdaten",
    "确切合约数据",
    "正確なコントラクトデータ",
    "정확한 계약 데이터",
  ],
  steps: [
    "Deposit → wait → collect shares",
    "Depositar → esperar → cobrar participaciones",
    "Depositar → aguardar → receber cotas",
    "Déposer → attendre → recevoir les parts",
    "Einzahlen → warten → Anteile abholen",
    "存款 → 等待 → 领取份额",
    "入金 → 待機 → 持分受取",
    "입금 → 대기 → 지분 수령",
  ],
} as const;
export type VaultCopyKey = keyof typeof words;
export const vaultKeys = Object.keys(words) as VaultCopyKey[];
export const vaultCopy = (locale: Locale) => (key: VaultCopyKey) =>
  words[key][locales.indexOf(locale)];
